"""Phase 0 → DPO parquet: consume verl K=8 rollout JSONL files, apply lex-rank
pair rule, build a parquet whose rows are DPO training samples
(prompt, chosen, rejected, info_mask_chosen, info_mask_rejected, difficulty, qid, domain).

The output parquet is consumed by the curriculum DPO trainer
(verl/trainer/dpo/train.py).

`info_mask_*` is a compressed run-length encoding of the agent-token mask
over the response: it marks 1 for tokens generated by the agent and 0 for
tokens injected as <information>...</information> environment observations.
This mirrors `ray_trainer.py:_create_loss_mask` on the PPO side.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, REPO_ROOT)

# Reuse the same feature extractor used for pair-yield analysis
from scripts.dpo.pair_yield import (  # noqa: E402
    compute_features,
    lex_score_v1,
    lex_score_v3,
    classify_yield,
    _diff_of,
    _gt_target,
    group_by_qid,
    load_records,
)

# Regex for <information>...</information> spans (non-greedy)
INFO_RE = re.compile(r"<information>.*?</information>", re.DOTALL)


def reconstruct_response(rec: Dict) -> Tuple[str, List[Tuple[int, int]]]:
    """Rebuild the full response string from the trace, plus per-info-block
    character spans (start, end) in that string.

    Verl trace schema: each turn dict has `prediction` (raw agent text, with
    <think>/<graph>/<answer> tags) and `observation` (env-injected
    "\\n\\n<information>...</information>\\n\\n" block).

    Returns (response_text, info_spans). info_spans are char intervals over
    response_text that should be MASKED OUT for DPO loss (loss_mask=0)."""
    trace = rec.get("trace") or []
    parts: List[str] = []
    info_spans: List[Tuple[int, int]] = []
    cursor = 0
    for t in trace:
        if not isinstance(t, dict):
            continue
        pred = t.get("prediction") or ""
        obs = t.get("observation") or ""
        if pred:
            parts.append(str(pred))
            cursor += len(str(pred))
        if obs:
            start = cursor
            parts.append(str(obs))
            cursor += len(str(obs))
            info_spans.append((start, cursor))
    return "".join(parts), info_spans


def info_mask_from_spans(text: str, spans: List[Tuple[int, int]]) -> List[int]:
    """Per-character mask (1=agent token, 0=info token).

    The trainer will tokenize `text` and apply this mask after re-projecting
    onto token boundaries. We deliver the char-level mask for portability;
    tokenization-aware projection happens in the trainer dataset class."""
    mask = [1] * len(text)
    for s, e in spans:
        for i in range(s, min(e, len(text))):
            mask[i] = 0
    return mask


def _prompt_of(rec: Dict) -> Any:
    """Return the prompt as stored in the parquet (list[dict] with 'role'/'content')."""
    return rec.get("prompt") or rec.get("question") or ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl_glob", required=True,
                    help="Glob over verl results.jsonl files. Quote it.")
    ap.add_argument("--train_parquet", required=True,
                    help="Original Academic train.parquet — used to look up the prompt field per qid")
    ap.add_argument("--out_parquet", required=True,
                    help="Output DPO training parquet path")
    ap.add_argument("--allow_partial_tie", action="store_true",
                    help="If set, also include L1_tie_partial pairs (where chosen and rejected differ only in tiebreak fields). Default off.")
    ap.add_argument("--max_turns", type=int, default=10)
    ap.add_argument("--lex_version", choices=["v1", "v3"], default="v3",
                    help="Lex tuple variant. v1 = original (em,eh,vf,-loop,-invalid,-ngr) used by phaseA-fixed-v1. v3 = redesigned (em,eh,vf,final_answer,-err_rate,-n_repeated). Default v3.")
    ap.add_argument("--pair_strategy", choices=["extreme", "marginal", "topboundary", "mix", "union", "et"], default="extreme",
                    help=("How to pick chosen vs rejected from K sorted scores. "
                          "extreme = rank-1 vs rank-K (default; current behavior). "
                          "marginal = rank-2 vs rank-(K-1) (NOTE: not actually marginal, just less extreme). "
                          "topboundary = best em=1 trace vs best em=0 trace (cleanest label, smallest meaningful gap; drops qids with all-em=1 or all-em=0). "
                          "mix = topboundary where available, extreme as fallback (preserves all qids that L1-classify). "
                          "union = output up to 3 distinct pairs per qid: extreme + topboundary (when available) + top2/bottom2 (when distinct from extreme)."))
    args = ap.parse_args()

    paths = sorted(glob.glob(args.jsonl_glob))
    if not paths:
        print(f"[FATAL] no files match {args.jsonl_glob}", file=sys.stderr)
        sys.exit(1)
    print(f"loading {len(paths)} JSONL files")
    records = load_records(paths)
    by_qid = group_by_qid(records)
    # Keys are now (domain, qid) tuples — see the note in
    # pair_yield.group_by_qid (cross-domain qid collision).
    print(f"unique (domain, qid) groups: {len(by_qid)}")

    # Build prompt lookup table from original train.parquet, keyed by
    # (domain, qid). The Academic train.parquet has multiple rows with the
    # same qid (one per sub-domain), so a qid-only lookup overwrites and
    # silently picks the wrong prompt.
    train_df = pd.read_parquet(args.train_parquet)
    prompt_by_dom_qid: Dict[Any, Any] = {}
    for _, row in train_df.iterrows():
        qid = row.get("qid")
        ei = row.get("extra_info")
        if hasattr(ei, "tolist"):
            try: ei = ei.tolist()
            except Exception: pass
        domain = ei.get("domain") if isinstance(ei, dict) else None
        prompt_by_dom_qid[(domain, qid)] = row.get("prompt")
    print(f"loaded {len(prompt_by_dom_qid)} (domain,qid) prompts from {args.train_parquet}")

    rows = []
    n_skipped_no_pair = 0
    n_skipped_no_prompt = 0
    n_kept = 0

    for key, recs in by_qid.items():
        domain, qid = key if isinstance(key, tuple) else (None, key)
        bucket = _diff_of(recs[0])
        feats = [compute_features(r, max_turns=args.max_turns) for r in recs]
        lex_fn = lex_score_v1 if args.lex_version == "v1" else lex_score_v3
        scores = [lex_fn(f) for f in feats]
        layer = classify_yield(scores)

        keep = (layer == "L1") or (args.allow_partial_tie and layer == "L1_tie_partial")
        if not keep:
            n_skipped_no_pair += 1
            continue

        # Pair selection: choose chosen_idx, rejected_idx based on strategy.
        # Sorted indices: descending score (best first).
        sorted_idx = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)
        K = len(sorted_idx)
        em1 = [i for i in sorted_idx if feats[i].get("em", 0) == 1]
        em0 = [i for i in sorted_idx if feats[i].get("em", 0) == 0]

        # Build list of candidate (chosen_idx, rejected_idx) pairs. For
        # single-pair strategies this list has length 1 (or 0 → skip).
        candidates = []

        if args.pair_strategy == "extreme":
            candidates.append((sorted_idx[0], sorted_idx[-1]))
        elif args.pair_strategy == "marginal":
            if K >= 4:
                candidates.append((sorted_idx[1], sorted_idx[-2]))
        elif args.pair_strategy == "topboundary":
            if em1 and em0:
                candidates.append((em1[0], em0[0]))
        elif args.pair_strategy == "mix":
            if em1 and em0:
                candidates.append((em1[0], em0[0]))
            else:
                candidates.append((sorted_idx[0], sorted_idx[-1]))
        elif args.pair_strategy == "et":
            # Extreme + Topboundary: union without the rank-2/rank-(K-1) tier.
            # Yields up to 2 pairs per qid; the lex-tuple dedup pass below
            # collapses duplicates so qids where extreme and topbound share
            # the same lex signature still produce only 1 pair.
            candidates.append((sorted_idx[0], sorted_idx[-1]))
            if em1 and em0:
                candidates.append((em1[0], em0[0]))
        elif args.pair_strategy == "union":
            # Up to 3 distinct pairs per qid:
            # 1) extreme: rank-1 vs rank-K (always available since L1)
            candidates.append((sorted_idx[0], sorted_idx[-1]))
            # 2) topboundary: best em=1 vs best em=0 (only if both exist)
            if em1 and em0:
                candidates.append((em1[0], em0[0]))
            # 3) top2/bottom2: rank-2 vs rank-(K-1) — only when top2 lex is
            #    STRICTLY LOWER than top1 (so it adds new "second-best" signal,
            #    not a tie-break duplicate of rank-1) AND bot2 lex is STRICTLY
            #    HIGHER than bot1 (likewise for the floor). This rules out the
            #    common K=16 case where 5 traces are em=1 (all lex-tied) and
            #    11 are em=0 (all lex-tied), which previously emitted a
            #    rank-2/rank-(K-1) pair carrying identical (chosen_lex,
            #    rejected_lex) signal as the extreme pair.
            if (K >= 4
                and scores[sorted_idx[1]] != scores[sorted_idx[0]]
                and scores[sorted_idx[-2]] != scores[sorted_idx[-1]]):
                candidates.append((sorted_idx[1], sorted_idx[-2]))
        else:
            raise ValueError(f"unknown pair_strategy: {args.pair_strategy}")

        # Deduplicate by (chosen_idx, rejected_idx), drop self-pairs.
        # Also dedup by (chosen_lex_tuple, rejected_lex_tuple): two pairs
        # backed by different trace samples but identical lex tuples carry
        # the SAME reward delta for DPO and just dilute gradient diversity
        # within a batch. Keep only one pair per distinct lex-signature.
        seen_idx = set()
        seen_sig = set()
        valid_pairs = []
        for ci, ri in candidates:
            if ci == ri:
                continue
            if (ci, ri) in seen_idx:
                continue
            sig = (scores[ci], scores[ri])
            if sig in seen_sig:
                continue
            seen_idx.add((ci, ri))
            seen_sig.add(sig)
            valid_pairs.append((ci, ri))

        if not valid_pairs:
            n_skipped_no_pair += 1
            continue

        prompt = prompt_by_dom_qid.get((domain, qid))
        if prompt is None:
            # Fallback: the JSONL might have the prompt or question stored
            prompt = _prompt_of(recs[valid_pairs[0][0]])
        if prompt is None or (isinstance(prompt, str) and not prompt):
            n_skipped_no_prompt += 1
            continue

        # Emit one row per valid pair (1-3 rows for union; 1 row for others)
        emitted_any = False
        for best_idx, worst_idx in valid_pairs:
            chosen_text, chosen_info_spans = reconstruct_response(recs[best_idx])
            rejected_text, rejected_info_spans = reconstruct_response(recs[worst_idx])
            if not chosen_text or not rejected_text:
                continue

            rows.append({
                "qid": qid,
                "difficulty": bucket,
                "domain": domain,
                "prompt": prompt,
                "chosen": chosen_text,
                "rejected": rejected_text,
                "chosen_info_spans": chosen_info_spans,
                "rejected_info_spans": rejected_info_spans,
                "chosen_features": feats[best_idx],
                "rejected_features": feats[worst_idx],
                # extra_info matches verl's parquet schema so the curriculum sampler
                # in crl_e2h.py reads `extra_info.difficulty` directly.
                "extra_info": {"difficulty": bucket, "qid": qid, "domain": domain},
            })
            n_kept += 1
            emitted_any = True
        if not emitted_any:
            n_skipped_no_pair += 1

    print(f"\nkept pairs: {n_kept}")
    print(f"skipped (no pair / tied): {n_skipped_no_pair}")
    print(f"skipped (no prompt found): {n_skipped_no_prompt}")
    if not rows:
        print("[FATAL] no pairs produced — check Phase 0 output and pair-yield analyzer first.", file=sys.stderr)
        sys.exit(1)

    out_df = pd.DataFrame(rows)
    print(f"\nbucket distribution in output parquet:")
    print(out_df["difficulty"].value_counts().to_dict())

    os.makedirs(os.path.dirname(args.out_parquet) or ".", exist_ok=True)
    out_df.to_parquet(args.out_parquet, index=False)
    print(f"\nwrote {len(out_df)} pairs to: {args.out_parquet}")


if __name__ == "__main__":
    main()
